import type { Metadata } from "next";
import { Inter, Noticia_Text, Anton } from "next/font/google";
import Header from "@/components/header";
import "./globals.css";
import { FeedProvider } from "@/context/feedContext";

const inter = Inter({ subsets: ["latin"] });
const noticia = Noticia_Text({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-noticia",
});
const arimo = Anton({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-anton",
});

export const metadata: Metadata = {
  title: "News Master",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${noticia.variable} ${arimo.variable}`}
      >
        <FeedProvider>
          <Header />
          {children}
        </FeedProvider>
      </body>
    </html>
  );
}
